"""Add ThreatEvent and ThreatScore models

Revision ID: 33d19cec7cfe
Revises: 8e1466178037
Create Date: 2026-08-15 20:19:27.676860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d19cec7cfe'
down_revision: Union[str, None] = '8e1466178037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_events_id'), 'threat_events', ['id'], unique=False)
    op.create_index(op.f('ix_threat_events_ip_address'), 'threat_events', ['ip_address'], unique=False)
    op.create_table('threat_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('threat_level', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('active_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_block_id'], ['threat_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scores_id'), 'threat_scores', ['id'], unique=False)
    op.create_index(op.f('ix_threat_scores_ip_address'), 'threat_scores', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_scores_ip_address'), table_name='threat_scores')
    op.drop_index(op.f('ix_threat_scores_id'), table_name='threat_scores')
    op.drop_table('threat_scores')
    op.drop_index(op.f('ix_threat_events_ip_address'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_id'), table_name='threat_events')
    op.drop_table('threat_events')
    # ### end Alembic commands ###
