"""Add ThreatBlock model

Revision ID: 8e1466178037
Revises: d63de5ef2173
Create Date: 2026-08-14 16:41:03.817312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1466178037'
down_revision: Union[str, None] = 'd63de5ef2173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_blocks_id'), 'threat_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_threat_blocks_ip_address'), 'threat_blocks', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_blocks_ip_address'), table_name='threat_blocks')
    op.drop_index(op.f('ix_threat_blocks_id'), table_name='threat_blocks')
    op.drop_table('threat_blocks')
    # ### end Alembic commands ###
